### ISSUE TITLE
Multiple falsely detected errors when there are multiple #options in an if statement

### ISSUE THREAD

**Issue by Riescent** [sgranade/choicescript_vscode#17]
```
1. *temp check true
2. 
3. *fake_choice
4. 	*if check = true
5. 		#Choice 1
6. 			You chose "Choice 1"
7. 		#Choice 2
8. 			You chose "Choice 2"
9. 		#Choice 3
10. 			You chose "Choice 3"
```

I've run this code without issue but:

At line 7, the error "Line is indented too far" is falsely detected
At line 9, the errors "Line is not indented far enough" and "An #option must only appear inside a *choice or *fake_choice (check that indention is correct)" are falsely detected

The same errors can be found when using *choice instead of *fake_choice despite the code running without issues:

```
1. *temp something true
2. 
3. *choice
4. 	*if something = true
5. 		#Choice 1
6. 			You chose "Choice 1"
7. 			*goto label
8. 		#Choice 2
9. 			You chose "Choice 2"
10. 			*goto label
11. 		#Choice 3
12. 			You chose "Choice 3"
13. 			*goto label
14. 
15. *label label
```

At line 8, the error "Line is indented too far" is falsely detected
At line 11, the errors "Line is not indented far enough" and "An #option must only appear inside a *choice or *fake_choice (check that indention is correct)" are falsely detected

**Comment by sgranade** [comment]
I didn't know that was legal! Cool. I'll update the parser to allow that.
